<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BelmontHotelSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     * Truncates all tables except users and creates Belmont Hotel in Palawan with rooms.
     */
    public function run(): void
    {
        // Truncate tables (except users)
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('reservations')->truncate();
        DB::table('payments')->truncate();
        DB::table('rooms')->truncate();
        DB::table('hotels')->truncate();
        DB::table('booking_queue')->truncate();
        DB::table('transaction_logs')->truncate();
        DB::table('promo_codes')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Create Belmont Hotel in Palawan
        $hotelId = DB::table('hotels')->insertGetId([
            'name' => 'Belmont Hotel',
            'description' => 'Luxurious beachfront resort in Palawan, surrounded by pristine lagoons and crystal-clear waters. Experience world-class hospitality in one of the Philippines\' most beautiful destinations.',
            'address' => 'El Nido, Palawan',
            'city' => 'Palawan',
            'country' => 'Philippines',
            'latitude' => 11.2048,
            'longitude' => 119.4406,
            'star_rating' => 5,
            'amenities' => json_encode([
                'Private Beach Access',
                'Infinity Pool',
                'Spa & Wellness Center',
                'Fine Dining Restaurant',
                'Pool Bar',
                'Water Sports Center',
                'Island Hopping Tours',
                'Snorkeling & Diving',
                'Kayaking',
                'Free WiFi',
                'Concierge Service',
                'Airport Transfer',
                'Parking',
                'Room Service',
                'Laundry Service'
            ]),
            'images' => json_encode(['belmont-palawan-1.jpg', 'belmont-palawan-2.jpg', 'belmont-palawan-3.jpg']),
            'hotelbeds_code' => 'BELMONT_PALAWAN',
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Create rooms
        $rooms = [
            // Junior Suites
            [
                'hotel_id' => $hotelId,
                'room_type' => 'Junior Suite, Balcony',
                'description' => 'Spacious junior suite featuring a private balcony with stunning views. Perfect for couples seeking comfort and elegance. The suite includes a separate sitting area and modern amenities.',
                'price_per_night' => 8500.00,
                'quantity' => 6,
                'available_quantity' => 6,
                'max_guests' => 2,
                'max_adults' => 2,
                'max_children' => 0,
                'amenities' => json_encode([
                    'Private Balcony',
                    'King Size Bed',
                    'Separate Sitting Area',
                    'Ocean View',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Mini Bar',
                    'Coffee Machine',
                    'Safe',
                    'Work Desk',
                    'Marble Bathroom',
                    'Premium Toiletries',
                    'Room Service'
                ]),
                'images' => json_encode(['junior-suite-balcony-1.jpg', 'junior-suite-balcony-2.jpg']),
                'size' => '45 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hotel_id' => $hotelId,
                'room_type' => 'Junior Suite, Lagoon Access',
                'description' => 'Luxurious junior suite with direct access to the pristine lagoon. Wake up to the sound of gentle waves and step directly into the crystal-clear waters from your private entrance.',
                'price_per_night' => 9500.00,
                'quantity' => 6,
                'available_quantity' => 6,
                'max_guests' => 2,
                'max_adults' => 2,
                'max_children' => 0,
                'amenities' => json_encode([
                    'Direct Lagoon Access',
                    'Private Entrance to Lagoon',
                    'King Size Bed',
                    'Separate Sitting Area',
                    'Lagoon View',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Mini Bar',
                    'Coffee Machine',
                    'Safe',
                    'Work Desk',
                    'Marble Bathroom',
                    'Premium Toiletries',
                    'Outdoor Shower',
                    'Room Service'
                ]),
                'images' => json_encode(['junior-suite-lagoon-1.jpg', 'junior-suite-lagoon-2.jpg']),
                'size' => '50 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 1 Bedroom Suites
            [
                'hotel_id' => $hotelId,
                'room_type' => '1 Bedroom Suite, Balcony',
                'description' => 'Elegant one-bedroom suite with a private balcony overlooking the ocean. Features a separate bedroom, spacious living area, and premium amenities. Ideal for couples or small families.',
                'price_per_night' => 12000.00,
                'quantity' => 6,
                'available_quantity' => 6,
                'max_guests' => 3,
                'max_adults' => 2,
                'max_children' => 1,
                'amenities' => json_encode([
                    'Private Balcony',
                    'Separate Bedroom',
                    'Living Room',
                    'King Size Bed',
                    'Sofa Bed',
                    'Ocean View',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Mini Bar',
                    'Coffee Machine',
                    'Kitchenette',
                    'Safe',
                    'Work Desk',
                    'Marble Bathroom',
                    'Premium Toiletries',
                    'Room Service'
                ]),
                'images' => json_encode(['1br-suite-balcony-1.jpg', '1br-suite-balcony-2.jpg']),
                'size' => '65 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hotel_id' => $hotelId,
                'room_type' => '1 Bedroom Suite, Lagoon Access',
                'description' => 'Exclusive one-bedroom suite with direct lagoon access. Features a separate bedroom, elegant living space, and your own private entrance to the pristine lagoon waters.',
                'price_per_night' => 13500.00,
                'quantity' => 6,
                'available_quantity' => 6,
                'max_guests' => 3,
                'max_adults' => 2,
                'max_children' => 1,
                'amenities' => json_encode([
                    'Direct Lagoon Access',
                    'Private Entrance to Lagoon',
                    'Separate Bedroom',
                    'Living Room',
                    'King Size Bed',
                    'Sofa Bed',
                    'Lagoon View',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Mini Bar',
                    'Coffee Machine',
                    'Kitchenette',
                    'Safe',
                    'Work Desk',
                    'Marble Bathroom',
                    'Premium Toiletries',
                    'Outdoor Shower',
                    'Room Service'
                ]),
                'images' => json_encode(['1br-suite-lagoon-1.jpg', '1br-suite-lagoon-2.jpg']),
                'size' => '70 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Signature Suite
            [
                'hotel_id' => $hotelId,
                'room_type' => 'Signature Suite, Pool Access',
                'description' => 'Our most luxurious suite featuring direct access to the infinity pool. This signature accommodation offers unparalleled elegance, spacious living areas, and premium services for the ultimate luxury experience.',
                'price_per_night' => 18000.00,
                'quantity' => 6,
                'available_quantity' => 6,
                'max_guests' => 4,
                'max_adults' => 3,
                'max_children' => 2,
                'amenities' => json_encode([
                    'Direct Pool Access',
                    'Infinity Pool View',
                    'Separate Bedroom',
                    'Spacious Living Room',
                    'Dining Area',
                    'King Size Bed',
                    'Sofa Bed',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Premium Mini Bar',
                    'Espresso Machine',
                    'Kitchenette',
                    'Safe',
                    'Work Desk',
                    'Marble Bathroom with Jacuzzi',
                    'Premium Toiletries',
                    'Butler Service',
                    'Complimentary Breakfast',
                    'Room Service'
                ]),
                'images' => json_encode(['signature-suite-1.jpg', 'signature-suite-2.jpg']),
                'size' => '85 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 2 Bedroom Suite
            [
                'hotel_id' => $hotelId,
                'room_type' => '2 Bedroom Suite, Lagoon Access',
                'description' => 'Spacious two-bedroom suite perfect for families or groups. Features direct lagoon access, two separate bedrooms, a large living area, and premium amenities. Ideal for up to 4 guests.',
                'price_per_night' => 22000.00,
                'quantity' => 3,
                'available_quantity' => 3,
                'max_guests' => 4,
                'max_adults' => 4,
                'max_children' => 2,
                'amenities' => json_encode([
                    'Direct Lagoon Access',
                    'Private Entrance to Lagoon',
                    'Two Separate Bedrooms',
                    'Spacious Living Room',
                    'Dining Area',
                    'Two King Size Beds',
                    'Sofa Bed',
                    'Lagoon View',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Premium Mini Bar',
                    'Coffee Machine',
                    'Full Kitchen',
                    'Safe',
                    'Work Desk',
                    'Two Marble Bathrooms',
                    'Premium Toiletries',
                    'Outdoor Shower',
                    'Room Service'
                ]),
                'images' => json_encode(['2br-suite-lagoon-1.jpg', '2br-suite-lagoon-2.jpg']),
                'size' => '120 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 1 Bedroom Villas
            [
                'hotel_id' => $hotelId,
                'room_type' => '1 Bedroom Villa, Garden View with Private Pool',
                'description' => 'Exclusive one-bedroom villa surrounded by lush tropical gardens. Features a private infinity pool, spacious outdoor terrace, and complete privacy. Perfect for a romantic getaway.',
                'price_per_night' => 25000.00,
                'quantity' => 4,
                'available_quantity' => 4,
                'max_guests' => 2,
                'max_adults' => 2,
                'max_children' => 0,
                'amenities' => json_encode([
                    'Private Infinity Pool',
                    'Garden View',
                    'Outdoor Terrace',
                    'Outdoor Dining Area',
                    'Separate Bedroom',
                    'Living Room',
                    'King Size Bed',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Premium Mini Bar',
                    'Espresso Machine',
                    'Full Kitchen',
                    'Safe',
                    'Work Desk',
                    'Marble Bathroom with Rain Shower',
                    'Premium Toiletries',
                    'Outdoor Shower',
                    'Private Garden',
                    'Butler Service',
                    'Complimentary Breakfast',
                    'Room Service'
                ]),
                'images' => json_encode(['1br-villa-garden-1.jpg', '1br-villa-garden-2.jpg']),
                'size' => '150 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hotel_id' => $hotelId,
                'room_type' => '1 Bedroom Villa, Resort View with Private Pool',
                'description' => 'Luxurious one-bedroom villa with panoramic resort views. Features a private pool, expansive outdoor space, and stunning vistas of the resort and surrounding landscape.',
                'price_per_night' => 25000.00,
                'quantity' => 4,
                'available_quantity' => 4,
                'max_guests' => 2,
                'max_adults' => 2,
                'max_children' => 0,
                'amenities' => json_encode([
                    'Private Infinity Pool',
                    'Resort View',
                    'Panoramic Views',
                    'Outdoor Terrace',
                    'Outdoor Dining Area',
                    'Separate Bedroom',
                    'Living Room',
                    'King Size Bed',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Premium Mini Bar',
                    'Espresso Machine',
                    'Full Kitchen',
                    'Safe',
                    'Work Desk',
                    'Marble Bathroom with Rain Shower',
                    'Premium Toiletries',
                    'Outdoor Shower',
                    'Butler Service',
                    'Complimentary Breakfast',
                    'Room Service'
                ]),
                'images' => json_encode(['1br-villa-resort-1.jpg', '1br-villa-resort-2.jpg']),
                'size' => '150 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hotel_id' => $hotelId,
                'room_type' => '1 Bedroom Villa, Ocean View with Private Pool',
                'description' => 'Stunning one-bedroom villa with breathtaking ocean views. Features a private infinity pool that seems to merge with the sea, creating an unforgettable luxury experience.',
                'price_per_night' => 28000.00,
                'quantity' => 4,
                'available_quantity' => 4,
                'max_guests' => 2,
                'max_adults' => 2,
                'max_children' => 0,
                'amenities' => json_encode([
                    'Private Infinity Pool',
                    'Ocean View',
                    'Panoramic Sea Views',
                    'Outdoor Terrace',
                    'Outdoor Dining Area',
                    'Separate Bedroom',
                    'Living Room',
                    'King Size Bed',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Premium Mini Bar',
                    'Espresso Machine',
                    'Full Kitchen',
                    'Safe',
                    'Work Desk',
                    'Marble Bathroom with Rain Shower',
                    'Premium Toiletries',
                    'Outdoor Shower',
                    'Butler Service',
                    'Complimentary Breakfast',
                    'Room Service'
                ]),
                'images' => json_encode(['1br-villa-ocean-1.jpg', '1br-villa-ocean-2.jpg']),
                'size' => '150 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hotel_id' => $hotelId,
                'room_type' => '1 Bedroom Villa, Ocean View with Balcony and Private Pool',
                'description' => 'Ultimate luxury one-bedroom villa featuring both a private infinity pool and a spacious balcony with panoramic ocean views. The perfect combination of indoor and outdoor living in paradise.',
                'price_per_night' => 30000.00,
                'quantity' => 4,
                'available_quantity' => 4,
                'max_guests' => 2,
                'max_adults' => 2,
                'max_children' => 0,
                'amenities' => json_encode([
                    'Private Infinity Pool',
                    'Spacious Balcony',
                    'Ocean View',
                    'Panoramic Sea Views',
                    'Outdoor Terrace',
                    'Outdoor Dining Area',
                    'Separate Bedroom',
                    'Living Room',
                    'King Size Bed',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Premium Mini Bar',
                    'Espresso Machine',
                    'Full Kitchen',
                    'Safe',
                    'Work Desk',
                    'Marble Bathroom with Rain Shower',
                    'Premium Toiletries',
                    'Outdoor Shower',
                    'Butler Service',
                    'Complimentary Breakfast',
                    'Room Service'
                ]),
                'images' => json_encode(['1br-villa-ocean-balcony-1.jpg', '1br-villa-ocean-balcony-2.jpg']),
                'size' => '160 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 2 Bedroom Villa
            [
                'hotel_id' => $hotelId,
                'room_type' => '2 Bedroom Villa, Ocean View with Balcony and Private Pool',
                'description' => 'Magnificent two-bedroom villa with stunning ocean views, private infinity pool, and spacious balconies. Perfect for families or groups seeking the ultimate luxury experience with complete privacy.',
                'price_per_night' => 45000.00,
                'quantity' => 2,
                'available_quantity' => 2,
                'max_guests' => 4,
                'max_adults' => 4,
                'max_children' => 2,
                'amenities' => json_encode([
                    'Private Infinity Pool',
                    'Spacious Balconies',
                    'Ocean View',
                    'Panoramic Sea Views',
                    'Outdoor Terrace',
                    'Outdoor Dining Area',
                    'Two Separate Bedrooms',
                    'Spacious Living Room',
                    'Dining Room',
                    'Two King Size Beds',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Premium Mini Bar',
                    'Espresso Machine',
                    'Full Kitchen',
                    'Safe',
                    'Work Desk',
                    'Two Marble Bathrooms with Rain Shower',
                    'Premium Toiletries',
                    'Outdoor Shower',
                    'Private Garden',
                    'Butler Service',
                    'Complimentary Breakfast',
                    'Room Service'
                ]),
                'images' => json_encode(['2br-villa-ocean-1.jpg', '2br-villa-ocean-2.jpg']),
                'size' => '200 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 3 Bedroom Villa
            [
                'hotel_id' => $hotelId,
                'room_type' => '3 Bedroom Villa, Ocean View with Private Pool',
                'description' => 'The ultimate luxury accommodation - a magnificent three-bedroom villa with breathtaking ocean views and a private infinity pool. This exclusive villa offers unparalleled space, privacy, and luxury for large families or groups.',
                'price_per_night' => 65000.00,
                'quantity' => 1,
                'available_quantity' => 1,
                'max_guests' => 6,
                'max_adults' => 6,
                'max_children' => 3,
                'amenities' => json_encode([
                    'Private Infinity Pool',
                    'Ocean View',
                    'Panoramic Sea Views',
                    'Expansive Outdoor Terrace',
                    'Outdoor Dining Area',
                    'Outdoor Lounge',
                    'Three Separate Bedrooms',
                    'Spacious Living Room',
                    'Formal Dining Room',
                    'Three King Size Beds',
                    'WiFi',
                    'Air Conditioning',
                    'Smart TV',
                    'Premium Mini Bar',
                    'Espresso Machine',
                    'Full Kitchen',
                    'Wine Cellar',
                    'Safe',
                    'Work Desk',
                    'Three Marble Bathrooms with Rain Shower',
                    'Premium Toiletries',
                    'Outdoor Shower',
                    'Private Garden',
                    'Dedicated Butler Service',
                    'Complimentary Breakfast',
                    'Complimentary Airport Transfer',
                    'Room Service'
                ]),
                'images' => json_encode(['3br-villa-ocean-1.jpg', '3br-villa-ocean-2.jpg']),
                'size' => '300 sqm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('rooms')->insert($rooms);
    }
}



